FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Start the development server with the correct host
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]