services:
  node_contacts:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./node/.env
    depends_on:
      mongodb_contacts:
        condition: service_healthy
    networks:
      - contacts_network

  mongodb_contacts:
    image: mongo:latest
    container_name: mongodb_contacts
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_contacts_data:/data/db
    networks:
      - contacts_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  remix_contacts:
    build:
      context: ./remix
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://node_contacts:8000
    env_file:
      - ./remix/.env
    networks:
      - contacts_network
    depends_on:
      mongodb_contacts:
        condition: service_healthy

volumes:
  mongodb_contacts_data:

networks:
  contacts_network:
    driver: bridge
